version: '3.8'

services:
  auth-service:
    build: ./backend/auth-service
    environment:
      NODE_ENV: development
    networks:
      - service_mynetwork
    ports:
      - "9000:9000"
    volumes:
      - ./backend/auth-service:/app
    restart: unless-stopped

  manage_projets_service:
    build: ./backend/manage_projets_service
    environment:
      NODE_ENV: development
    networks:
      - service_mynetwork
    ports:
      - "9001:9001"
    volumes:
      - ./backend/manage_projets_service:/app
    restart: unless-stopped
  
  frontend-gestion-projets:
    build: ./frontend/frontend-gestion-projets
    environment:
      - REACT_APP_API_AUTH_URL=http://localhost:9000/api/v1
      - REACT_APP_API_PROJECT_URL=http://localhost:9001/api/v1
    networks:
      - service_mynetwork
    ports:
      - "4001:4001"
    restart: unless-stopped

networks:
  service_mynetwork:
    driver: bridge