
version: '3.8'

services:
  auth-service:
    build: ./backend/auth-service
    environment:
      NODE_ENV: development
      ENV_FILE: .env.auth-service
    networks:
      - service_mynetwork
    ports:
      - "9000:9000"
    volumes:
      - ./backend/auth-service:/app
    restart: unless-stopped

  manage_projets_service:
    build: ./backend/manage_projets_service
    environment:
      NODE_ENV: development
      ENV_FILE: .env.manage_projets_service
    networks:
      - service_mynetwork
    ports:
      - "9001:9001"
    volumes:
      - ./backend/manage_projets_service:/app
    restart: unless-stopped

networks:
  service_mynetwork:
    driver: bridge
